name: ✨ Feature request
description: Suggest a feature or enhancement
labels: [type:enhancement, "status:needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature or enhancement ❤️
  - type: checkboxes
    attributes:
      label: Checklist
      description: Please confirm and check all the following options.
      options:
        - label: I have searched the [existing issues](https://github.com/lukasmasuch/streamlit-pydantic/issues) for similar feature requests.
          required: true
        - label: I added a descriptive title and summary to this issue.
          required: true
  - type: textarea
    attributes:
      label: Summary
      description: Type here a clear and concise description of the feature or enhancement request. Aim for 2-3 sentences.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why?
      description: Please outline the problem, motivation, or use case related to this feature request.
      placeholder: |
        I'm always frustrated when ...
    validations:
      required: false
  - type: textarea
    attributes:
      label: How?
      description: |
        Please describe the solution or implementation you'd like to see.
        Don't worry if you don't have a clear solution in mind; any input helps!
      placeholder: |
        Introduce a new command called `sp.pydantic_foo` with the following set of parameters...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Links? References? Anything that will give us more context about the feature request here!

        _Tip: You can attach images by clicking this area to highlight it and then dragging files in._
    validations:
      required: false
