name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rye
        uses: eifinger/setup-rye@v4
      - name: Install dependencies
        run: | # abort if the lockfile changes
          rye sync
          [[ -n $(git diff --stat requirements.lock) ]] && exit 1
      - name: Run linters
        run: rye lint

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rye
        uses: eifinger/setup-rye@v4
      - name: Install dependencies
        run: |  # abort if the lockfile changes
            rye sync
            [[ -n $(git diff --stat requirements.lock) ]] && exit 1
      - name: Run tests
        run: rye test
